--CREATE TABLE EMPLOYEE--

CREATE TABLE EMPLOYEE
(
	EMPNO INT,
	EMPNAME VARCHAR(25),
	JOININGDATA DATETIME,
	SALARY DECIMAL(8,2),
	CITY VARCHAR(20)
);


--INSERT THE RECORDS--

--1--

INSERT INTO EMPLOYEE
VALUES (101,'KEYUR','5-JAN-02',12000.00,'RAJKOT');

--2--

INSERT INTO EMPLOYEE
VALUES (102,'HARDIK','15-FEB-04',14000.00,'AHMEDABAD');

--3--

INSERT INTO EMPLOYEE
VALUES (103,'KAJAL','14-MAR-06',15000.00,'BARODA');

--4--

INSERT INTO EMPLOYEE
VALUES (104,'BHOOMI','23-JUN-05',12500.00,'AHMEDABAD');

--5--

INSERT INTO EMPLOYEE
VALUES (102,'HARMIT','15-FEB-04',14000.00,'RAJKOT');

SELECT * FROM EMPLOYEE;

--DELETE RECORDS--

--1--

DELETE FROM EMPLOYEE
WHERE SALARY>=14000;

--2--

DELETE FROM EMPLOYEE
WHERE CITY='RAJKOT';

--3--

DELETE FROM EMPLOYEE
WHERE JOININGDATA>'01-JAN-07';

--4--

TRUNCATE TABLE EMPLOYEE;

--5--

DROP TABLE EMPLOYEE;

SELECT * FROM EMPLOYEE;